---
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.1.0a1
    hooks:
      - id: ansible-lint
        # yaml is already checked with yamllint above
        # role-name will require fixing
        args: ['-x', 'role-name,yaml']
