---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "m3aggregator"
    id: "m3aggregator"
    address: "{{ private_ip }}"
    port: 6002
    checks:
      - tcp: "{{ private_ip }}:6002"
        interval: "10s"
