{
 "title": "Observe Cortex - system",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "component",
    "query": "compactor,distributor,flusher,ingester,purger,querier,query-frontend,query-scheduler,ruler,store-gateway,lb"
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"cortex.*\", instance=~\"cortex-$component.*\"}, instance)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=~\"$node\", device!=\"lo\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "component" },
  {
   "title": "CPU user",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\", instance=~\"cortex-$component.*\", mode=\"user\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"cortex-$component.*\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"cortex-$component.*\", instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"cortex-$component.*\", instance=~\"$node\"} - (node_memory_Cached_bytes{instance=~\"cortex-$component.*\", instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"cortex-$component.*\", instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$node\", instance=~\"cortex-$component.*\", device=~\"$device\"}[5m])*8) by (instance)",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "sum(-1 * irate(node_network_transmit_bytes_total{instance=~\"$node\", instance=~\"cortex-$component.*\", device=~\"$device\"}[5m])*8) by (instance)",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  }
 ]
}