{
 "title": "Observe Cortex - global",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Labels per sample",
   "type": "timeseries",
   "description": "bucket view",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_labels_per_sample_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_labels_per_sample_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cortex_labels_per_sample_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_labels_per_sample_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Blocks count",
   "type": "timeseries",
   "description": "total number of blocks in the bucket (including blocks marked for deletion)",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(cortex_bucket_blocks_count)"
    }
   ]
  },
  {
   "title": "Blocks failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(cortex_bucket_store_block_load_failures_total)"
    }
   ]
  },
  {
   "title": "Blocks cleaned",
   "type": "timeseries",
   "description": "by compactor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(cortex_compactor_blocks_cleaned_total{instance=~\"cortex-compactor-.*\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}