{
 "title": "Observe Cortex - writes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_request_duration_seconds_count{job=\"cortex\", instance=~\"cortex-distributor.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\")) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Send latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_ingester_client_request_duration_seconds_bucket{instance=~\"cortex-distributor-.*\",operation=\"/cortex.Ingester/Push\"}[2m])) by (le)) * 1e3",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_ingester_client_request_duration_seconds_bucket{instance=~\"cortex-distributor-.*\",operation=\"/cortex.Ingester/Push\"}[2m])) by (le)) * 1e3",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum(rate(cortex_ingester_client_request_duration_seconds_sum{instance=~\"cortex-distributor-.*\",operation=\"/cortex.Ingester/Push\"}[2m])) * 1e3 / sum(rate(cortex_ingester_client_request_duration_seconds_count{instance=~\"cortex-distributor-.*\",operation=\"/cortex.Ingester/Push\"}[2m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Inflight saturation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((cortex_distributor_inflight_push_requests{instance=~\"cortex-distributor-.\"} * 100) / on(instance) cortex_distributor_instance_limits{instance=~\"cortex-distributor-.*\",limit=\"max_inflight_push_requests\"})",
     "legendFormat": "{{ ingester }}"
    }
   ]
  },
  {
   "title": "Sample ingestion rate",
   "type": "timeseries",
   "description": "from distributor point of view",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (cortex_distributor_ingestion_rate_samples_per_second{instance=~\"cortex-distributor-.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_distributor_query_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_distributor_query_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_distributor_query_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_request_duration_seconds_count{job=\"cortex\", instance=~\"cortex-ingester.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\")) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Inflight saturation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((cortex_ingester_inflight_push_requests{instance=~\"cortex-ingester-.\"} * 100) / on(instance) cortex_ingester_instance_limits{instance=~\"cortex-ingester-.*\",limit=\"max_inflight_push_requests\"})",
     "legendFormat": "{{ ingester }}"
    }
   ]
  },
  {
   "title": "Sample ingestion rate",
   "type": "timeseries",
   "description": "from ingester point of view",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (cortex_ingester_ingestion_rate_samples_per_second{instance=~\"cortex-ingester-.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}