{
 "title": "observes promscale",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Data flow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "batching",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promscale_metric_batcher_flush_series_count[5m])",
       "legendFormat": "metric_batcher_flush_series"
      },
      {
       "expr": "rate(promscale_copier_inserts_per_batch_count[5m])",
       "legendFormat": "copier_inserts_per_batch"
      },
      {
       "expr": "rate(promscale_copier_rows_per_batch_count[5m])",
       "legendFormat": "copier_rows_per_batch_count"
      },
      {
       "expr": "rate(promscale_copier_rows_per_insert_count[5m])",
       "legendFormat": "copier_rows_per_insert"
      }
     ]
    },
    {
     "title": "data flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "promscale_metric_batcher_channel_cap",
       "legendFormat": "metric_batcher_channel_cap"
      },
      {
       "expr": "rate(promscale_metric_batcher_channel_len_count[5m])",
       "legendFormat": "metric_batcher_channel_len"
      },
      { "expr": "promscale_copier_channel_cap", "legendFormat": "copier_channel_cap" },
      { "expr": "promscale_copier_channel_len", "legendFormat": "copier_channel_len" }
     ]
    },
    {
     "title": "statement_cache_elements_stored",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promscale_statement_cache_elements_stored_count[5m])",
       "legendFormat": "statement_cache_elements_stored"
      }
     ]
    }
   ]
  },
  {
   "title": "Database performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(promscale_copier_insert_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(promscale_copier_insert_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(promscale_copier_insert_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "tup_inserted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{datname=\"timescale\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate metric_name cache eviction/total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promscale_metric_name_cache_evictions_total[5m])",
       "legendFormat": "metric_name_cache_evictions_total"
      },
      {
       "expr": "promscale_metric_name_cache_capacity",
       "legendFormat": "metric_name_cache_capacity"
      }
     ]
    },
    {
     "title": "Rate label cache eviction/total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promscale_label_cache_evictions_total[5m])",
       "legendFormat": "label_cache_evictions_total"
      },
      { "expr": "promscale_label_cache_capacity", "legendFormat": " label_cache_capacity" }
     ]
    },
    {
     "title": "Rate series cache eviction/total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promscale_series_cache_evictions_total[5m])",
       "legendFormat": "series_cache_evictions_total"
      },
      {
       "expr": "promscale_series_cache_capacity",
       "legendFormat": " series_cache_capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "metric_batcher channel",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(promscale_metric_batcher_channel_len_bucket[5m])) by (le))",
       "legendFormat": "metric batcher len p99"
      },
      {
       "expr": "promscale_metric_batcher_channel_cap",
       "legendFormat": "metric_batcher_channel capacity"
      }
     ]
    },
    {
     "title": "Copier channel queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "promscale_copier_channel_len/promscale_copier_channel_cap",
       "legendFormat": "copier ration len/cap"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "load 1",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"(promscale|patroni.*node).*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"(promscale|patroni.*node).*\"} - node_memory_MemFree_bytes{instance=~\"(promscale|patroni.*node).*\"} - (node_memory_Cached_bytes{instance=~\"(promscale|patroni.*node).*\"} + node_memory_Buffers_bytes{instance=~\"(promscale|patroni.*node).*\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"(promscale|patroni.*node).*\"}[5m])) by (instance)",
       "legendFormat": "{{instance}} - Read bytes"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"(promscale|patroni.*node).*\"}[5m])) by (instance)",
       "legendFormat": "{{instance}} - Written bytes"
      }
     ]
    }
   ]
  }
 ]
}