{
 "title": "troubleshoot promscale",
 "time": { "from": "now-12h", "to": "now-1m" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "promscale",
    "label": "promscale",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"promscale.*\"}, instance)"
    }
   },
   {
    "name": "prometheus",
    "label": "prometheus",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"prometheus.*\"}, instance)"
    }
   },
   {
    "name": "postgresql",
    "label": "postgresql",
    "query": {
     "query": "label_values(up{job=~\"postgres.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "(Prom) sample Ingestion rate / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Retried samples / min",
   "type": "graph",
   "description": "Total number of samples which failed on send to remote storage but were retried because the send error was recoverable.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_samples_retried_total[5m])) by (remote_name)",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Pending samples",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_remote_storage_samples_pending) by (remote_name)",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Samples successfully  sent / seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n\nrate(prometheus_remote_storage_samples_total[5m])\n\n) by (remote_name)",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "remote_storage_shards_desired",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{}"
    }
   ]
  },
  { "title": "Promscale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Promscale sample rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promscale_sent_samples_total[5m])",
     "legendFormat": "{{instance}} sent"
    },
    {
     "expr": "rate(promscale_received_samples_total[5m])",
     "legendFormat": "{{instance}} received"
    }
   ]
  },
  {
   "title": "Promscale memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$promscale\"} - \nnode_memory_MemFree_bytes{instance=~\"$promscale\"} - \n(node_memory_Cached_bytes{instance=~\"$promscale\"} + node_memory_Buffers_bytes{instance=~\"$promscale\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "promscale cache",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promscale_label_cache_capacity{}",
     "legendFormat": "label_cache_capacity"
    },
    {
     "expr": "promscale_label_cache_elements_stored{}",
     "legendFormat": "label_cache_elements_stored"
    },
    {
     "expr": "promscale_metric_name_cache_capacity{}",
     "legendFormat": "metric_name_cache_capacity"
    },
    {
     "expr": "promscale_metric_name_cache_elements_stored{}",
     "legendFormat": "metric_name_cache_elements_stored"
    }
   ]
  },
  { "title": "Postgresql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "tup_inserted",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"timescale\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "checkpoints",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{instance=~\"$postgresql\"}[30s])",
     "legendFormat": "checkpoint_sync - {{ instance }}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{instance=~\"$postgresql\"}[30s])",
     "legendFormat": "checkpoint_write - {{ instance }}"
    }
   ]
  },
  {
   "title": "checkpoints_req",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_req{instance=~\"$postgresql\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$postgresql\"}[5m])",
     "legendFormat": "{{device}} - Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$postgresql\"}[5m])",
     "legendFormat": "{{device}} - Write time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$postgresql\"}[5m])",
     "legendFormat": "{{instance}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$postgresql\"}[5m])",
     "legendFormat": "{{instance}} - Writes completed"
    }
   ]
  }
 ]
}