{
 "title": "troubleshoot remote write",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "remote_name",
    "query": {
     "query": "label_values(prometheus_remote_storage_max_samples_per_send, remote_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_remote_storage_shards_max{remote_name=~\"$remote_name\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAL",
   "type": "table",
   "description": "the WAL segment file that Prometheus is currently writing new data to.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_segment_current{job=\"prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time diff between TSDB and Remote storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_highest_timestamp_in_seconds{instance=~\"$instance\"} - on (job, instance) prometheus_remote_storage_queue_highest_sent_timestamp_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of desired shards",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending samples",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_samples_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Retry samples",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_retried_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$remote_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "remote_name" },
  {
   "title": "WAL",
   "type": "table",
   "description": "shows the current WAL segment file that each remote write instance is currently reading from. This metric can be compared to the following one as the first step to determining if remote write is falling behind.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "prometheus_wal_watcher_current_segment{job=\"prometheus\", consumer=\"$remote_name\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "shards",
   "type": "timeseries",
   "description": "current: how many shards are currently running\nmin/max: the min/max shards based on your current configuration\ndesired: show us how many shards the sharding calculation wants to run based on the throughput",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{job=\"prometheus\", remote_name=\"$remote_name\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - current"
    },
    {
     "expr": "prometheus_remote_storage_shards_desired{job=\"prometheus\", remote_name=\"$remote_name\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - desired"
    }
   ]
  },
  {
   "title": "batch send duration",
   "type": "timeseries",
   "description": "This is a histogram of latency for sending to the remote endpoint",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"prometheus\", remote_name=\"$remote_name\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"prometheus\", remote_name=\"$remote_name\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"prometheus\", remote_name=\"$remote_name\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"prometheus\", remote_name=\"$remote_name\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}